/*
 * Copyright (c) 1999, 2000, 2001 Sonic Software Corporation. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Progress Software Corporation.
 * ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use it only in accordance with the
 * terms of the license agreement you entered into with Progress.
 *
 * PROGRESS MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, EITHER EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. PROGRESS SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY
 * LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 */

/*
 * public Interface ITRScriptListener
 *
 *	Defines the interface for listening to script output generated by a
 *  TRScriptLauncher.
 *
 *	Author: Colin MacNaughton (cmacnaug@progresss.com)
 *	Since: 01/03/00
 */

package org.fusesource.testrunner;

/**
 * Java programs that utilized a TRScriptLauncher can register themselves to be
 * notified when a new line is printed to the scripts output stream.
 * 
 * @author Colin MacNaughton (cmacnaug@progress.com)
 * @version 1.0
 * @since 1.0
 * @see TRScriptLauncher
 */
public interface ITRScriptListener {

    /**
     * The notify call back
     * 
     * @param trsl
     *            The TRScriptLauncher the output originates from.
     * @param output
     *            The line of output from the process.
     */
    //A notify for each new line of output generate by the script launched by
    //TRScriptLauncher
    public abstract void scriptOutputNotify(TRScriptLauncher trsl, String output);
}